env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@wordpress/eslint-plugin/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
globals:
  jQuery: readonly
  ClipboardJS: readonly
  toastr: readonly
rules:
  no-unused-vars:
    - error
    - args: none
