extends:
  - 'eslint:recommended'
  - 'plugin:@wordpress/eslint-plugin/recommended'
parser: '@babel/eslint-parser'
globals:
  jQuery: readonly
  ClipboardJS: readonly
  toastr: readonly
  ScrollTrigger: readonly
rules:
  no-unused-vars:
    - error
    - args: none
